### ISSUE TITLE
Nextjs: error command failed

### ISSUE THREAD

**Issue by indrasenareddy91** [sapics/ip-location-api#7]
"ip-location-api": "^2.1.3",
 hi there!
 its seems like there is a bug [ i rechecked by using another ip library but its working fine]
 Using this library in my nextjs backend

**Comment by sapics** [comment]
Thanks for finding error! I try to fix in 2.1.4, could you try it?

**Comment by indrasenareddy91** [comment]
hey idk if its my end basically the error is module not found 
import { lookup } from 'ip-location-api' // imported in my code
updated using npm [ aka npm i ip-location-api]

**Comment by sapics** [comment]
I have no experience in nextjs. Could you make any test case?

**Comment by indrasenareddy91** [comment]
![Screenshot 2024-10-11 211937](https://github.com/user-attachments/assets/d2d1715c-479e-4243-8d08-ce35469af42a)
![Screenshot 2024-10-11 211949](https://github.com/user-attachments/assets/953a0461-3781-46e3-8c34-9df3cc95b3f6)
![image](https://github.com/user-attachments/assets/13b1baee-3af4-424e-bd8b-a450f6b1c368)
i have never writtern test cases even unit ones too[ i am more of a beginner]
its working fine with other npm ip packages ive tested it out and for some reasons i've have to do testing on production

**Comment by sapics** [comment]
Thanks for additional information! I am looking into it.

**Comment by sapics** [comment]
I guess that there are no file "/varcel/path0/node_modules/ip-location-api/script/updatedb.mjs".
It might be located somewhere else.
Could you find where "ip-location-api" folder exists?

**Comment by indrasenareddy91** [comment]
In my local file structure its inside /node_modules/ip-location-api/script/updatedb.mjs [ directly under the root ]
myfoldername/node_modules/ip-location-api/script/updatedb.mjs

**Comment by sapics** [comment]
If your local file structure includes some spaces, it might be fixed v2.1.5.
If it dose not fixed in newer version, we would be better to wait for someone's help to fix this issue.

**Comment by indrasenareddy91** [comment]
alright! typescript is complaining that there no types for update.mjs or some other too [ i dont think its causing the issue]

**Comment by sapics** [comment]
I have renamed title, because original error was fixed.

**Comment by sapics** [comment]
Thank you for the detailed description!
I add new configuration ILA_API_DIR in v2.2.0.

I guess that it would work with following settings.

```bash
ILA_API_DIR=/your_directory/node_modules/ip-location-api
ILA_DATA_DIR=/your_directory/node_modules/ip-location-api/data
ILA_TMP_DATA_DIR=/your_directory/node_modules/ip-location-api/tmp
```

**Comment by peterkunsay** [comment]
Hello,

Thank you @sapics for the super fast update! However, unfortunately, this did not resolve the issue.

After further investigation, I concluded that Next.js (and Webpack) cannot bundle the library correctly. In the standalone build, only the following files are present:
![image](https://github.com/user-attachments/assets/986106a8-5533-49a3-b31b-3873a625173b)

With
```
outputFileTracingIncludes: {
      '**': [
        './node_modules/.pnpm/ip-location-api@*/**/*',
      ],
    }, 
```
I can force Next.js to include the full library, and the original error will cease to exist. However, the dependencies (or the dependencies of dependencies) will not be included in the bundle.

The current log when I do NOT modify anything inside the next conf regarding ip-location-api. Basically treat as a new install of the library: 

```
2024-10-23T13:34:16.778040259Z   ▲ Next.js 15.0.0-canary.173
2024-10-23T13:34:16.778342194Z   - Local:        http://76c1e2d261d2:3008
2024-10-23T13:34:16.778354667Z   - Network:      http://192.168.112.3:3008
2024-10-23T13:34:16.780845845Z 
2024-10-23T13:34:16.782997043Z  ✓ Starting...
2024-10-23T13:34:16.980476294Z  ✓ Ready in 1049ms
2024-10-23T13:34:19.136353700Z Database creating ...
2024-10-23T13:34:19.210261463Z node:internal/modules/cjs/loader:1228
2024-10-23T13:34:19.210311991Z   throw err;
2024-10-23T13:34:19.210315576Z   ^
2024-10-23T13:34:19.210318146Z 
2024-10-23T13:34:19.210320715Z Error: Cannot find module '/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/script/updatedb.mjs'
2024-10-23T13:34:19.210328773Z     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
2024-10-23T13:34:19.210331523Z     at Module._load (node:internal/modules/cjs/loader:1051:27)
2024-10-23T13:34:19.210333781Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
2024-10-23T13:34:19.210336353Z     at node:internal/main/run_main_module:28:49 {
2024-10-23T13:34:19.210338685Z   code: 'MODULE_NOT_FOUND',
2024-10-23T13:34:19.210340865Z   requireStack: []
2024-10-23T13:34:19.210343524Z }
2024-10-23T13:34:19.210345675Z 
2024-10-23T13:34:19.210348357Z Node.js v20.18.0
2024-10-23T13:34:19.215196886Z Error: Command failed: node /app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/script/updatedb.mjs ILA_FIELDS=country ILA_DATA_DIR=/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/data ILA_TMP_DATA_DIR=/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/tmp ILA_API_DIR=/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api ILA_AUTO_UPDATE="15 1 0 * * wed,sat"
2024-10-23T13:34:19.215241154Z node:internal/modules/cjs/loader:1228
2024-10-23T13:34:19.215245640Z   throw err;
2024-10-23T13:34:19.215248605Z   ^
2024-10-23T13:34:19.215251213Z 
2024-10-23T13:34:19.215253584Z Error: Cannot find module '/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/script/updatedb.mjs'
2024-10-23T13:34:19.215255990Z     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
2024-10-23T13:34:19.215258427Z     at Module._load (node:internal/modules/cjs/loader:1051:27)
2024-10-23T13:34:19.215260837Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
2024-10-23T13:34:19.215263089Z     at node:internal/main/run_main_module:28:49 {
2024-10-23T13:34:19.215265704Z   code: 'MODULE_NOT_FOUND',
2024-10-23T13:34:19.215267998Z   requireStack: []
2024-10-23T13:34:19.215270460Z }
2024-10-23T13:34:19.215272844Z 
2024-10-23T13:34:19.215287552Z Database created
2024-10-23T13:34:19.215305156Z Node.js v20.18.0
2024-10-23T13:34:19.215309207Z 
2024-10-23T13:34:19.215311847Z     at genericNodeError (node:internal/errors:984:15)
2024-10-23T13:34:19.215333070Z     at wrappedFn (node:internal/errors:538:14)
2024-10-23T13:34:19.215335686Z     at checkExecSyncError (node:child_process:891:11)
2024-10-23T13:34:19.215337458Z     at execSync (node:child_process:963:15)
2024-10-23T13:34:19.215339090Z     at updateDb (/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/cjs/main.cjs:313:17)
2024-10-23T13:34:19.215340874Z     at reload (/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/cjs/main.cjs:140:4)
2024-10-23T13:34:19.215342608Z     at Object.<anonymous> (/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/cjs/main.cjs:500:1)
2024-10-23T13:34:19.215345194Z     at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024-10-23T13:34:19.215346844Z     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024-10-23T13:34:19.215348386Z     at Module.load (node:internal/modules/cjs/loader:1288:32) {
2024-10-23T13:34:19.215350093Z   status: 1,
2024-10-23T13:34:19.215351787Z   signal: null,
2024-10-23T13:34:19.215353446Z   output: [
2024-10-23T13:34:19.215355094Z     null,
2024-10-23T13:34:19.215356573Z     <Buffer >,
2024-10-23T13:34:19.215358351Z     <Buffer 6e 6f 64 65 3a 69 6e 74 65 72 6e 61 6c 2f 6d 6f 64 75 6c 65 73 2f 63 6a 73 2f 6c 6f 61 64 65 72 3a 31 32 32 38 0a 20 20 74 68 72 6f 77 20 65 72 72 3b ... 474 more bytes>
2024-10-23T13:34:19.215396425Z   ],
2024-10-23T13:34:19.215398196Z   pid: 18,
2024-10-23T13:34:19.215399685Z   stdout: <Buffer >,
2024-10-23T13:34:19.215403881Z   stderr: <Buffer 6e 6f 64 65 3a 69 6e 74 65 72 6e 61 6c 2f 6d 6f 64 75 6c 65 73 2f 63 6a 73 2f 6c 6f 61 64 65 72 3a 31 32 32 38 0a 20 20 74 68 72 6f 77 20 65 72 72 3b ... 474 more bytes>
2024-10-23T13:34:19.215405821Z }
2024-10-23T13:34:19.239397025Z Error: ENOENT: no such file or directory, open '/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/data/g/4-1.dat'
2024-10-23T13:34:19.239429561Z     at Object.openSync (node:fs:573:18)
2024-10-23T13:34:19.239431991Z     at Object.readFileSync (node:fs:452:35)
2024-10-23T13:34:19.239433786Z     at reload (/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/cjs/main.cjs:143:21)
2024-10-23T13:34:19.239435684Z     at Object.<anonymous> (/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/cjs/main.cjs:500:1)
2024-10-23T13:34:19.239438181Z     at Module._compile (node:internal/modules/cjs/loader:1469:14)
2024-10-23T13:34:19.239440127Z     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
2024-10-23T13:34:19.239453767Z     at Module.load (node:internal/modules/cjs/loader:1288:32)
2024-10-23T13:34:19.239455567Z     at Module._load (node:internal/modules/cjs/loader:1104:12)
2024-10-23T13:34:19.239457129Z     at Module.require (node:internal/modules/cjs/loader:1311:19)
2024-10-23T13:34:19.239458845Z     at mod.require (/app/node_modules/.pnpm/next@15.0.0-canary.173_@babel+core@7.24.5_babel-plugin-react-compiler@0.0.0-experimental-734b_6lchyen7lknlof7hxw7c3t2gru/node_modules/next/dist/server/require-hook.js:65:28) {
2024-10-23T13:34:19.239460755Z   errno: -2,
2024-10-23T13:34:19.239462191Z   code: 'ENOENT',
2024-10-23T13:34:19.239463702Z   syscall: 'open',
2024-10-23T13:34:19.239465376Z   path: '/app/node_modules/.pnpm/ip-location-api@2.2.0/node_modules/ip-location-api/data/g/4-1.dat'
2024-10-23T13:34:19.239467055Z }
```

**Comment by sapics** [comment]
Could you `npm install ip-location-api` in other directory in production environment?

**Comment by peterkunsay** [comment]
Thank you for the answer!

My project uses Next.js and pnpm along with some other libraries. I build the project using GitLab's pipelines, which essentially:

- Installs pnpm
- Sets up environment variables from GitLab CI/CD
- Installs the project from the GitLab repository
- Builds the Next.js standalone version using Next.js (Webpack) <---- The issue happens here
- Copies some media-related folders and files
- Bundles everything into a Docker image
- The image is then downloaded and run

Therefore, I can't manually run `npm install` or `pnpm install` after the build, since Next.js already bundles everything into a standalone build, which only includes the used `node_modules` to save space. I suspect the issue arises here because it seems that Next.js can't correctly trace `ip-location-api`'s dependencies and/or imports.

**Comment by sapics** [comment]
Thanks for explanation!

In ip-location-api, we need 6 files as following.
```
4-1.dat
4-2.dat
4-3.dat
6-1.dat
6-2.dat
6-3.dat
```

Could you includes these files in any place?

If it is possible, it would work with following settings.

```
ILA_DATA_DIR=/your_data_directory
autoUpdate=false
```

**Comment by peterkunsay** [comment]
Thank you again for the answer!

I could manually copy data files during the build steps, so that wouldn't be a problem. The main issue is that the dependencies of `ip-location-api`, and some parts of `ip-location-api` itself, are missing. They are not included in the build because Next.js cannot properly trace the imports and / or dependecies. 

I can force Nextjs to include the full `ip-location-api` library in the standalone build with: 
```
outputFileTracingIncludes: {
      '**': [
        './node_modules/.pnpm/ip-location-api@*/**/*',
      ],
    }, 
```
    
in the Next.js conf., but the dependecies of  `ip-location-api`  will be missing.

**Comment by sapics** [comment]
If you can include above `.dat` files, it is not necessary to include files like `script/updatedb.mjs` or `src/db.mjs`.

**Comment by peterkunsay** [comment]
As I can see the `.dat` files are not present until the first start of the project, that is when it tries to download and throws the errors.

**Comment by sapics** [comment]
```
For me it runs completelly fine on dev mode, the issues only arise in the standalone version`
```

Could you copy `.dat` files which is created in dev mode?

**Comment by sapics** [comment]
Sorry, I will sleep soon. I will make a response tomorrow.

**Comment by peterkunsay** [comment]
Unfortunatelly I can not, since I build everything using gitlab pipelines, therefore the whole project is a fully clean install every time I build. 

No problem, thank you for the help, and good night!

**Comment by peterkunsay** [comment]
Hello,

I tested it, and it works perfectly without any issues! Super nice work—thank you so much for your help. I truly appreciate your time and effort!

**Comment by sapics** [comment]
Thank you for quick checking! Glad to hear it worked well!

**Comment by sapics** [comment]
I have added description in README about module bundler.
I close this issue as completed.

**Comment by indrasenareddy91** [comment]
seems like its not working [ about my prev comment ive checked previous logs and thaugt its working]
using  
import { lookup } from "ip-location-api/pack";
    var location = lookup(ip);

![image](https://github.com/user-attachments/assets/c3f23713-59b5-4a35-be03-45f59c84f370)

**Comment by indrasenareddy91** [comment]
hey there this issue is not fully resolved
using it in nextjs 15
installed ur latest package via
used this
 import { lookup } from 'ip-location-api/pack'
 even just importing this is causing the error [ spent 2 hours finding what is causing the error] 
[sorry about the other comment i looked into another deployment logs and taught it was working]
![image](https://github.com/user-attachments/assets/fea6c172-8193-46f1-bbd0-fb16ee1e623b)

**Comment by indrasenareddy91** [comment]
hey there this issue is not fully resolved
using it in nextjs 15
installed ur latest package via npm
used this..
 import { lookup } from 'ip-location-api/pack'
 even just importing this is causing the error [ spent 2 hours finding what is causing the error] 
[sorry about the other comment i looked into another deployment logs and taught it was working]
![image](https://github.com/user-attachments/assets/fea6c172-8193-46f1-bbd0-fb16ee1e623b)

**Comment by JClackett** [comment]
also getting the above, 

⨯ Error: ENOENT: no such file or directory, mkdir '/vercel'
    at async v (.next/server/app/(home)/profile/sessions/page.js:4:76879)
    at async A (.next/server/app/(home)/profile/sessions/page.js:4:41404)
    at async (.next/server/app/(home)/profile/sessions/page.js:4:45529) {
